@echo off
rem jython.bat		Version 1.2	28-Sep-2010	(bzm)
rem
rem This file starts jython extended with jMusic on a Windows system.  
rem The idea is to put everything needed, including jMusic and jython itself, 
rem within one directory to facilitate ease of instalation and execution.
rem
rem Note: This file is based on the batch file generated by the Jython installer.

rem Accumulate all arguments
set ARGS=

:loop
if [%1] == [] goto end
        set ARGS=%ARGS% %1
        shift
        goto loop
:end

REM using jMusic 1.7.0 with Gervill and Java 6 - see http://stackoverflow.com/questions/7749172/why-java-midi-synth-on-mac-stop-playing-notes
REM also with imgscalr – Java Image Scaling Library
java -Xmx1024m "-Dpython.home=." -classpath "%CD%\library;%CD%\library\jython2.5.3\jython.jar;%CD%\library\jython2.5.3\Lib;%CD%\library\jMusic1.7\jmusic.jar;%CD%\library\jMusic1.7\inst;%CD%\library\jsyn\jsyn.jar;%CD%\library\imgscalr-lib-4.2\imgscalr-lib-4.2.jar;%CD%\library\javaosc-core.jar%CLASSPATH%"  org.python.util.jython %ARGS% 

REM using jMusic 1.7 and Java 7
REM java -Xmx1024m "-Dsun.sound.useNewAudioEngine=true" "-Dpython.home=." -classpath "%CD%\library;%CD%\library\jython2.5.3\jython.jar;%CD%\library\jython2.5.3\Lib;%CD%\library\jMusic1.7\jmusic.jar;%CD%\library\jMusic1.7\inst;%CD%\library\jsyn\jsyn.jar;%CD%\library\javaosc-core.jar%CLASSPATH%"  org.python.util.jython %ARGS%

REM Using Gervill with jMusic 1.7 and Java 6 - see http://stackoverflow.com/questions/7749172/why-java-midi-synth-on-mac-stop-playing-notes
REM java -Xmx1024m "-Dsun.sound.useNewAudioEngine=true" "-Dpython.home=." -classpath "%CD%\library;%CD%\library\jython2.5.3\jython.jar;%CD%\library\jython2.5.3\Lib;%CD%\library\jMusic1.7\jmusic.jar;%CD%\library\jMusic1.7\inst;%CD%\library\jsyn\jsyn.jar;%CD%\library\javaosc-core.jar%CLASSPATH%"  org.python.util.jython %ARGS%

REM using jMusic 1.6.4
REM java -Xmx1024m "-Dpython.home=." -classpath "%CD%\library;%CD%\library\jython2.5.3\jython.jar;%CD%\library\jython2.5.3\Lib;%CD%\library\jMusic1.6.4\jmusic.jar;%CD%\library\jMusic1.6.4\inst;%CD%\library\jsyn\jsyn.jar;%CD%\library\javaosc-core.jar%CLASSPATH%" org.python.util.jython %ARGS%

REM Using Gervill with Java 6 - see http://stackoverflow.com/questions/7749172/why-java-midi-synth-on-mac-stop-playing-notes
REM java -Xmx4096m "-Dsun.sound.useNewAudioEngine=true" "-Dpython.home=." -classpath "%CD%\library;%CD%\library\jython2.5.3\jython.jar;%CD%\library\jython2.5.3\Lib;%CD%\library\jMusic1.6.4\jmusic.jar;%CD%\library\jMusic1.6.4\inst;%CD%\library\jsyn\jsyn.jar;%CD%\library\javaosc-core.jar%CLASSPATH%" org.python.util.jython %ARGS%

REM java -Xmx4096m "-Dpython.home=%CD%\library" -classpath "%CD%\library;%CD%\library\jython2.5.3\jython.jar;%CD%\library\jython2.5.3\Lib;%CD%\library\jMusic1.6.4\jmusic.jar;%CD%\library\jMusic1.6.4\inst;%CD%\library\jsyn\jsyn.jar;%CLASSPATH%" org.python.util.jython %ARGS%

REM java -Xmx4096m "-Dpython.home=%CD%\library" -classpath "%CD%\library;%CD%\library\jython2.5.3\jython.jar;%CD%\library\jython2.5.3\Lib;%CD%\library\jMusic1.6.4\jmusic.jar;%CD%\library\jMusic1.6.4\inst;%CD%\library\jsyn\jsyn.jar;%CLASSPATH%" org.python.util.jython %ARGS%

rem java "-Dpython.home=%CD%\library" -classpath "%CD%\library;%CD%\library\jython2.5.3\jython.jar;%CD%\library\jython2.5.3\Lib;%CD%\library\jMusic1.6.4\jmusic.jar;%CD%\library\jMusic1.6.4\inst;%CD%\library\jsyn\jsyn.jar;%CLASSPATH%" org.python.util.jython %ARGS%

